sudo: true
install:
  - pip install -r requirements/test.txt
language: python
python:
  - "3.6"
env: 
  - DJANGO_SETTINGS_MODULE=geekbeacon.settings.dev DJANGO_SECRET_KEY=secret DJANGO_ALLOWED_HOSTS=django 
script:
  - pytest # or py.test for Python versions 3.5 and below
