version: '2'

services:
  django: &django
    image: geekbeacon/django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - rabbit
    env_file: .env
    command: /gunicorn.sh

  postgres:
    image: geekbeacon/postgres
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    env_file: .env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
      - ./volumes/postgres_backup:/backups

  www:
    image: geekbeacon/nginx
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./compose/production/nginx/config:/etc/nginx/conf.d
    depends_on:
      - django
  memcached:
    image: memcached:latest
  rabbit:
    image: rabbitmq:latest
    env_file: .env
  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker.sh
  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat.sh
